/* eslint-disable import/no-extraneous-dependencies */
// Importing the withBundleAnalyzer function from '@next/bundle-analyzer' package
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  // Configuration for bundle analyzer plugin
  enabled: process.env.ANALYZE === 'true', // Enable bundle analyzer if ANALYZE environment variable is set to 'true'
});

// Exporting a Higher Order Component (HOC) generated by withBundleAnalyzer
module.exports = withBundleAnalyzer({
  // Configuration options for Next.js
  eslint: {
    dirs: ['.'], // Specify directories to run ESLint on
  },
  poweredByHeader: false, // Disable the "powered by Next.js" header in the response
  trailingSlash: true, // Enable trailing slashes in generated URLs
  basePath: '', // Base path for the application (empty string indicates root)
  output: 'standalone', // Output configuration for Next.js (standalone indicates each page as a standalone HTML file)
  // The starter code loads resources from the `public` folder with `router.basePath` in React components.
  // So, the source code is "basePath-ready".
  // You can remove `basePath` if you don't need it.
  reactStrictMode: true, // Enable React strict mode
});
