// Importing Document, Head, Html, Main, and NextScript components from 'next/document' package
import Document, { Head, Html, Main, NextScript } from 'next/document';

// Importing AppConfig from the '../utils/AppConfig' file
import { AppConfig } from '../utils/AppConfig';

// Need to create a custom _document because i18n support is not compatible with `next export`.
class MyDocument extends Document {
  // Override the render method to customize the HTML document structure
  // eslint-disable-next-line class-methods-use-this
  render() {
    return (
      // Rendering the HTML document with the specified language from AppConfig
      <Html lang={AppConfig.locale}>
        {/* Head component for including meta tags and other document head elements */}
        <Head />
        {/* Body component containing the main content of the page */}
        <body>
          {/* Main component for rendering the main content of the page */}
          <Main />
          {/* NextScript component for including scripts generated by Next.js */}
          <NextScript />
        </body>
      </Html>
    );
  }
}

// Exporting the MyDocument component as the default export for use in the application
export default MyDocument;
